--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.2.58.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 4/10/2017 8:20:05 PM
-- Server version: 5.7.18-log
-- Client version: 4.1
--


--
-- Definition for database sistemajudicial
--
DROP DATABASE IF EXISTS sistemajudicial;
CREATE DATABASE sistemajudicial
	CHARACTER SET utf8
	COLLATE utf8_general_ci;

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE sistemajudicial;

--
-- Definition for table caso
--
CREATE TABLE caso (
  id INT(11) NOT NULL AUTO_INCREMENT,
  numero VARCHAR(20) DEFAULT NULL,
  descripcion VARCHAR(200) DEFAULT NULL,
  id_quellerarte INT(11) DEFAULT NULL,
  id_juez INT(11) DEFAULT NULL,
  estado VARCHAR(50) DEFAULT NULL,
  fecha DATE DEFAULT NULL,
  historial VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table juez
--
CREATE TABLE juez (
  id INT(11) NOT NULL AUTO_INCREMENT,
  cedula VARCHAR(15) DEFAULT NULL,
  nombre VARCHAR(50) DEFAULT NULL,
  apellidos VARCHAR(50) DEFAULT NULL,
  telefono VARCHAR(20) DEFAULT NULL,
  sala VARCHAR(20) DEFAULT NULL,
  usuario VARCHAR(20) DEFAULT NULL,
  clave VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table quellerarte
--
CREATE TABLE quellerarte (
  id INT(11) DEFAULT NULL,
  cedula VARCHAR(255) DEFAULT NULL,
  nombre VARCHAR(255) DEFAULT NULL,
  apellidos VARCHAR(255) DEFAULT NULL,
  telefono VARCHAR(255) DEFAULT NULL,
  direccion VARCHAR(255) DEFAULT NULL
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

-- 
-- Dumping data for table caso
--

-- Table sistemajudicial.caso does not contain any data (it is empty)

-- 
-- Dumping data for table juez
--

-- Table sistemajudicial.juez does not contain any data (it is empty)

-- 
-- Dumping data for table quellerarte
--

-- Table sistemajudicial.quellerarte does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;